# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# Nastavitev, da je velikost za primere kode manjša - če želiš drugačno velikost samo spremeni footnotesize
from sphinx.highlighting import PygmentsBridge
from pygments.formatters.latex import LatexFormatter


class CustomLatexFormatter(LatexFormatter):
    def __init__(self, **options):
        super(CustomLatexFormatter, self).__init__(**options)
        self.verboptions = r"formatcom=\scriptsize"


PygmentsBridge.latex_formatter = CustomLatexFormatter

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('../..'))
numfig = True


# -- Project information -----------------------------------------------------

project = 'Dokumentacija za generiranje nalog'
copyright = '2019, Ursa'
author = 'Ursa'

# The full version, including alpha/beta/rc tags
release = '1.1'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx.ext.autodoc', 'sphinx_autorun', 'sphinxcontrib.bibtex'
              ]


# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'sl'

source_encoding = 'utf-8-sig'
autorun_languages = {
    'pycon': 'python -',
    'pycon_prefix_chars': 4,
    'pycon_input_encoding': 'utf-8',
    'pycon_output_encoding': 'utf-8',
    'pycon_show_source': False,
}

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# Latex nastavitve
latex_elements = {'figure_align': 'H', }

latex_toplevel_sectioning = 'section'
numfig_format = {}
numfig_format = {'section': '%s', 'figure': 'Slika %s', 'table': 'Tabela %s', 'code-block': 'Koda %s'}



# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'classic'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

autoclass_contetnt = 'both'
